global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using MediatR;
global using FluentAssertions;
global using Microsoft.AspNetCore.Mvc;
global using System.Threading;

global using Microsoft.Extensions.Options;
global using Moq;
global using Xunit;
global using API.Controllers;
global using API.Utils.Configs;
global using API.DataLayer.DTOs;
global using API.DataLayer.Models;
global using API.DataLayer.Queries.Users;
global using API.DataLayer.Contexts;